name: creación de artefactos de nodejs

on:
  push:
    branches:
      - master
      - develop

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip Folder
        run: zip -r result.zip . -x ".git/*" ".github/*" ".gitignore*"
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
