name: creación de artefactos de nodejs

on: push


jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: customer-server/ delivery-server/ esb-module/ restaurant-server/ package.json README.md
          dest: artifacts/result.zip  
